default: &default
  host: db
  username: root
  password: 123456
  pool: 5

development:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  database: app_development

  redis:
    host: 127.0.0.1
    port: 6379
    db: 0
    options:
      namespace: app_development
      expires_in: 86400
      compress: false

test:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  database: app_test

production:
  <<: *default
  encoding: unicode
  adapter: postgresql
  database: app_production
  username: postgre
  password: 
